---
- name: Install and configure Apache web server on Ubuntu
  hosts: apache01
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running and enabled at boot
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy a basic index.html
      copy:
        content: "<html><body><h1>Apache is working on EC2!</h1></body></html>"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

