---
  - hosts: database
    become: true
    tasks:
      - name: Install the latest version of MySQL
        apt:
          name: mysql-server
          state: present
          update_cache: yes

      - name: Ensure Apache is running and enabled at boot
        service:
          name: apache2
          state: started
          enabled: yes

